#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Avalon >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Avalon=/luci-static/avalon
		set luci.main.mediaurlbase=/luci-static/avalon
		commit luci
	EOF
fi

exit 0
